# Generated by Django 3.0.2 on 2020-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_desc', models.CharField(max_length=300)),
                ('pro_date', models.DateField()),
            ],
        ),
    ]
