# Generated by Django 3.0.2 on 2020-04-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categary',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='shop///images'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategary',
            field=models.CharField(default='', max_length=300),
        ),
    ]
